config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'

  resources :users
  resources :courses do
    resources :enrollments, only: %i[index new create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :enrollments, dependent: :destroy
  has_many :users, through: :enrollments
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  has_many :enrollments, dependent: :destroy
  has_many :courses, through: :enrollments

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy]

  def index
    @courses = Course.all
  end

  def show; end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to @course
    else
      render :new
    end
  end

  def edit; end

  def update
    if @course.update(course_params)
      redirect_to @course
    else
      render :edit
    end
  end

  def destroy
    @course.destroy
    redirect_to root_path
  end

  private

  def course_params
    params.require(:course).permit(:name)
  end

  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_course

  def index
    # @enrollments = @course.enrollments
    @teachers = @course.enrollments.where(role: "teacher")
    @tas = @course.enrollments.where(role: "ta")
    @students = @course.enrollments.where(role: "student")
  end

  def new
    @users = User.all - @course.users
    @enrollment = @course.enrollments.new
  end

  def create
    @enrollment = @course.enrollments.new(enrollment_params)
    if @enrollment.save
      redirect_to course_enrollments_path(@course)
    else
      render :new
    end
  end

  def destroy
    @course.enrollments.find(params[:id]).destroy
    redirect_to course_enrollments_path(@course)
  end

  private

  def enrollment_params
    params.require(:enrollment).permit(:role, :user_id)
  end

  def set_course
    @course = Course.find(params[:course_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: obj, local: true, class: 'ui form') do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: 'Course name' %>
  </div>

  <%= f.submit nil, class: 'ui blue button' %>
<% end %>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>
<%= render 'form', obj: @course %>

app/views/courses/index.html.erb
<h1 class="ui header">Courses</h1>
<h2><%= @courses.length <= 0 ? 'No Courses' : "" %></h2>
<ul>
  <% @courses.each do |course| %>
    <li>
      <%= link_to course.name, course %>
    </li>
  <% end %>
</ul>

app/views/courses/new.html.erb
<h1>Add Course</h1>
<%= render 'form', obj: @course %>

app/views/courses/show.html.erb
<h1><%= @course.name %></h1>
<%= link_to 'Enrollments', course_enrollments_path(@course) %>
<hr />
<h2>Users</h2>
<ul>
  <% @course.users.each do |user| %>
    <li>
      <%= link_to user.full_name, user %>
    </li>
  <% end %>
</ul>
<br />
<%= link_to 'Edit Course', edit_course_path(@course), class: 'ui info button' %>
<%= link_to 'Delete Course', @course, method: :delete, class: 'ui red button' %>

app/views/enrollments/index.html.erb
<h1><%= @course.name %> Enrollments</h1>
<%= link_to 'Add Enrollment', new_course_enrollment_path(@course) %>
<hr />

<h2>Teacher</h2>
<ul>
  <% @teachers.each do |t| %>
    <li>
      <%= t.user.full_name %>
      <br />
      <%= link_to 'Remove', [@course, t], method: :delete %>
    </li>
  <% end %>
</ul>

<h2>Ta</h2>
<ul>
  <% @tas.each do |t| %>
    <li>
      <%= t.user.full_name %>
      <br />
      <%= link_to 'Remove', [@course, t], method: :delete %>
    </li>
  <% end %>
</ul>

<h2>Student</h2>
<ul>
  <% @students.each do |s| %>
    <li>
      <%= s.user.full_name %>
      <br />
      <%= link_to 'Remove', [@course, s], method: :delete %>
    </li>
  <% end %>
</ul>

app/views/enrollments/new.html.erb
<h1>Add Enrollments</h1>

<%= form_with(model: [@course, @enrollment], local: true, class: 'ui form') do |f| %>
  <div class="field">
    <%= f.label :user %>
    <%= f.select :user_id, @users.collect { |u| [u.full_name, u.id] } %>
  </div>

  <div class="field">
    <%= f.label :role %>
    <%= f.select :role, ['ta', 'teacher', 'student'] %>
  </div>

  <%= f.submit nil, class: 'ui blue button'%>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <li>
      <%= link_to 'Courses', courses_path %>
    </li>
    <li>
      <%= link_to 'Add Course', new_course_path %>
    </li>
    <li>
      <%= link_to 'Users', users_path %>
    </li>
    <li>
      <%= link_to 'Add User', new_user_path %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learning Management System</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: obj, local: true, class: 'ui form') do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, autofocus: true, placeholder: 'First name' %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, placeholder: 'Last name' %>
  </div>

  <%= f.submit nil, class: 'ui blue button' %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render 'form', obj: @user %>

app/views/users/index.html.erb
<h1 class="ui header">Users</h1>
<h2><%= @users.length <= 0 ? 'No Users' : "" %></h2>
<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.full_name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Add User</h1>
<%= render 'form', obj: @user %>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>
<hr />
<h2>Courses</h2>
<ul>
  <% @user.courses.each do |course| %>
    <li>
      <%= link_to course.name, course %>
    </li>
  <% end %>
</ul>
<br />
<%= link_to 'Edit User', edit_user_path(@user), class: 'ui info button' %>
<%= link_to 'Delete User', @user, method: :delete, class: 'ui red button' %>